# Generated by Django 5.2.8 on 2025-11-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='articulo',
            new_name='tipo',
        ),
    ]
